spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sqlDemo
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl