spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl